---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: '{{ .Release.Name }}-postgres'
  labels:
    # TODO: Use templates
    app.kubernetes.io/name: paperless-ng
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  serviceName: '{{ .Release.Name }}-postgres'
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: '{{.Values.image.postgres.repository}}:{{.Values.image.postgres.tag}}'
          ports:
          - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "paperless"
            - name: POSTGRES_USER
              value: "paperless"
            - name: POSTGRES_PASSWORD
              value: "paperless"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: '{{ .Release.Name }}-postgres'
  volumeClaimTemplates:
    - metadata:
        name: '{{ .Release.Name }}-postgres'
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: '{{ .Values.persistence.storageClassName}}'
        resources:
          requests:
            storage: 1Gi