---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-redis'
  labels:
    # TODO: Use templates
    app.kubernetes.io/name: paperless-ng
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      # TODO: Use templates
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: '{{.Values.image.redis.repository}}:{{.Values.image.redis.tag}}'
        ports:
        - containerPort: 6379