---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-redis'
  labels:
    # TODO: Use templates
    app.kubernetes.io/name: paperless-ng
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379